# Generated by Django 4.2.6 on 2023-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinhvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], max_length=5)),
                ('tuoi', models.SmallIntegerField()),
                ('diem_toan', models.SmallIntegerField()),
                ('diem_ly', models.SmallIntegerField()),
                ('diem_hoa', models.SmallIntegerField()),
                ('diem_tb', models.SmallIntegerField()),
                ('hoc_luc', models.CharField(choices=[('Gioi', 'Gioi'), ('Kha', 'Kha'), ('TrungBinh', 'Trungbinh'), ('Kem', 'Kem')], max_length=20)),
            ],
        ),
    ]
