# Generated by Django 4.2.6 on 2023-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='diem_tb',
            field=models.FloatField(),
        ),
    ]
