# Generated by Django 4.2.6 on 2023-10-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_sinhvien_diem_tb'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sinhvien',
            table='sinhvien',
        ),
    ]
